export default {
  // Session
  RESTORE_SESSION_SUCCESS: 'RESTORE_SESSION_SUCCESS',
  UPDATE_SESSION_SUCCESS: 'UPDATE_SESSION_SUCCESS',
  // Room
  FIND_ROOM_SUCCESS: 'FIND_ROOM_SUCCESS',
  CLEAR_ROOM_DATA: 'CLEAR_ROOM_DATA',
  NEW_MESSAGE_POSTED: 'NEW_MESSAGE_POSTED',
  ROOM_MESSAGE_EDITED: 'ROOM_MESSAGE_EDITED',
  // Message
  FIND_MESSAGE_SUCCESS: 'FIND_MESSAGE_SUCCESS',
  CLEAR_MESSAGE_DATA: 'CLEAR_MESSAGE_DATA',
  SET_MESSAGE_EDITING: 'SET_MESSAGE_EDITING',
};
